### ISSUE TITLE
Bug ao incluir biblioteca sem um nome específico de variável

### ISSUE THREAD

**Issue by aquila0101** [DesignLiquido/portugol-studio#9]
Ao rodar esse código no portugol studio tenho um erro na extensão:

```
programa
{

inclua biblioteca Matematica
real a1, a2, a3, a4, a5, a6, a7
caracter b1, b2 ,b3 ,b4 ,b5 , b6, b7

funcao inicio()
{

escreva("Temos Açai e Tapioca\n Escreva A para Açai ou T para Tapioca")
leia(b1)
se(b1 =='A')
{
escreva("O açai custa R$ 18,00 Quantos você gostaria? ")
leia(a1)
a2 = a1*18
escreva("O Pagamento é via Pix? S (Sim) ou N (Não)")
leia(b2)

se(b2 =='S' e b1 =='A')
escreva("Você ganhou 15% de Desconto O Valor Total é: ", a2*15/100)
senao se(b2 == 'N' e b1 =='A' )
escreva("Você ganhou 10% de Desconto O Valor Total é: ", a2*10/100)

}

se(b1 =='T')
{
escreva("O tapioca custa R$ 12,00 Quantas você gostaria? ")
leia(a3)
a4 = a3*18
escreva("O Pagamento é via Pix? S (Sim) ou N (Não)")
leia(b3)

se(b3 =='S' e b1 =='A')
escreva("Você ganhou 15% de Desconto O Valor Total é: ", a3*18*15/100)
senao se(b3 == 'N' e b1 =='A' )
escreva("Você ganhou 10% de Desconto O Valor Total é: ", a3*18*10/100)

}



}
}
```

```

Error: Variável não definida: 'inclua'.
	at PilhaEscoposExecucaoPortugolStudio.obterValorVariavel (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:49262:15)
	at InterpretadorPortugolStudioComDepuracao2.procurarVariavel (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:11332:42)
	at InterpretadorPortugolStudioComDepuracao2.visitarExpressaoDeVariavel (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:11335:21)
	at Variavel.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:2508:42)
	at InterpretadorPortugolStudioComDepuracao2.avaliar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:12009:32)
	at InterpretadorPortugolStudioComDepuracao2.visitarDeclaracaoDeExpressao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:11338:27)
	at Expressao.aceitar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:2873:32)
	at InterpretadorPortugolStudioComDepuracao2.executar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:12340:33)
	at InterpretadorPortugolStudioComDepuracao2.executarUltimoEscopoComandoContinuar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:12268:42)
	at InterpretadorPortugolStudioComDepuracao2.instrucaoContinuarInterpretacao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:12300:20)
	at InterpretadorPortugolStudioComDepuracao2.instrucaoContinuarInterpretacao (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:49360:45)
	at DeleguaTempoExecucaoLocal.iniciar (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:159147:26)
	at DeleguaSessaoDepuracaoLocal.launchRequest (/home/aquila/.var/app/com.vscodium.codium/data/codium/extensions/designliquido.designliquido-vscode-0.10.17-universal/dist/extensao.js:159364:26)
```

**Comment by aquila0101** [comment]
Atualizei o código e esse funciona mais o outro só no portugol studio



```
programa
{
	
real acai, tapioca, ac1, ac2
	caracter a1, a2, a3 
	funcao inicio()
	{
		escreva("Temos Açai e Tapioca\n Escreva A para Açai ou T para Tapioca: ")
		leia(a1)
		se(a1 =='A')
		{
		
		escreva("O açai custa é R$ 12,00 Quantos você Gostaria: ")
		leia(acai)
		ac1 = acai*18
		escreva("Gostaria de Pagar via Pix? S (sim) ou N (não)")
		leia(a2)
		se(a2=='S' e ac1 >= 100.00)
		escreva("Você ganhou 15% de Desconto!\n O Valor Total é R$ ", ac1*0.15)
		senao se(a2=='N' e ac1 < 100.00 ou a2=='S')
		escreva("Você Não ganhou nenhum desconto\n O Valor Total é R$", ac1)
		senao se(a2=='N' e ac1 >= 100.00)
		escreva("Você ganhou 10% de Desconto!\n O Valor Total é R$ ", ac1*0.10)
		
		
		}
		se(a1 =='T')
		{

			escreva("A Tapioca custa R$ 18,00 Quantas você Gostaria: ")
		     leia(tapioca)
		     ac2 = tapioca*18
		     escreva("Gostaria de Pagar via Pix? S (sim) ou N (não)")
			leia(a3)
			se(ac2 >= 100.00 e a3 =='S')
			escreva("Você ganhou 15% de Desconto!\n O Valor Total é R$ ", ac2*0.15)
			senao se(ac2 < 100.00 e a3 =='S' ou a3=='N')
			escreva("Voçê nao ganhou nehum desconto\n O Valor Total é R$ ", ac2)
			senao se(ac2 >= 100.00 e a3 =='N')
			escreva("Você ganhou 10% de Desconto!\n O Valor Total é R$ ", ac2*0.10)

			
		}

		se(a1 != 'A' e a1 != 'T')
		escreva("Escreva somente A para Açai e T para Tapioca")
		
	}
}

```

**Comment by leonelsanchesdasilva** [comment]
@aquila0101 Lancei versão da biblioteca matemática hoje, na versão 0.10.18 da extensão. Era bom testar para ver se preciso ajustar alguma coisa. Se puder fazer, por favor, e me retornar aqui, agradeço muito.

**Comment by aquila0101** [comment]
![Captura de tela de 2024-04-06 16-03-29](https://github.com/DesignLiquido/portugol-studio/assets/162712945/dc613dcc-8728-4cf9-8d8f-ca2817630771)
![Captura de tela de 2024-04-06 16-02-45](https://github.com/DesignLiquido/portugol-studio/assets/162712945/af0ab54d-7b95-4bd5-aa68-b4ca49ab8c79)
